const qs=new URLSearchParams(location.search),p=KS_DATA.products.find(x=>x.slug===qs.get('p'))||KS_DATA.products[0];
const gallery=[{src:p.image,fallback:p.fallback},{src:p.hover,fallback:p.hoverFallback},...KS_DATA.productGallery.filter(x=>x.src!==p.image&&x.src!==p.hover)];
const proText={
  zh:{intro:'以日常穿着的舒适度为核心，采用高密度棉混纺面料，兼顾柔软触感、挺括轮廓与耐穿性。表面经过轻微磨毛处理，视觉更柔和，同时保留清晰的服装结构。',fit:'整体为宽松箱型轮廓，肩线略微下落，胸围留有充足活动量。建议偏好标准效果选择常规尺码，偏好更松弛层次感可选择大一码。',fabric:'主体使用高密度棉混纺针织面料，内层触感细腻；领口与袖口采用高回弹罗纹组织，重点受力位置进行加固车缝，提升长期穿着稳定性。',care:'建议冷水或30°C以下轻柔机洗；反面装洗衣袋；使用中性洗涤剂；不可漂白；阴凉处自然晾干；低温熨烫并避开印花及胶章区域。',color:'Charcoal 为偏低饱和的炭灰黑，Cloud Cream 为带暖感的奶油白。不同屏幕、光线与拍摄环境可能产生轻微色差，实际颜色以实物为准。',style:'炭灰适合与黑色、洗水牛仔、灰调下装组合；奶油白更适合搭配棕色、卡其和浅蓝牛仔。通过同色系叠穿可以强化系列的安静、松弛感。'},
  zht:{intro:'以日常穿著的舒適度為核心，採用高密度棉混紡面料，兼顧柔軟觸感、挺括輪廓與耐穿性。表面經過輕微磨毛處理，視覺更柔和，同時保留清晰的服裝結構。',fit:'整體為寬鬆箱型輪廓，肩線略微下落，胸圍留有充足活動量。偏好標準效果可選常規尺碼，偏好更鬆弛層次感可選大一碼。',fabric:'主體使用高密度棉混紡針織面料，內層觸感細膩；領口與袖口採用高回彈羅紋組織，重點受力位置進行加固車縫。',care:'建議冷水或30°C以下輕柔機洗；反面裝洗衣袋；使用中性洗滌劑；不可漂白；陰涼處自然晾乾；低溫熨燙並避開印花及膠章。',color:'Charcoal 為低飽和炭灰黑，Cloud Cream 為帶暖感奶油白。不同螢幕、光線與拍攝環境可能產生輕微色差，實際顏色以實物為準。',style:'炭灰適合黑色、洗水牛仔、灰調下裝；奶油白適合棕色、卡其和淺藍牛仔。同色系疊穿可強化系列的安靜與鬆弛感。'},
  en:{intro:'Designed around everyday comfort, this piece uses a dense cotton-blend knit that balances softness, structure and durability. A lightly brushed surface gives the fabric a softer visual finish while preserving a clean silhouette.',fit:'Relaxed boxy fit with a slightly dropped shoulder and generous ease through the chest. Choose your regular size for the intended fit, or size up for a more oversized layered look.',fabric:'Dense cotton-blend knit with a soft inner hand. High-recovery rib is used at key openings, while stress points are reinforced for better shape retention over time.',care:'Cold or gentle wash below 30°C. Turn inside out and use a laundry bag. Use mild detergent, do not bleach, air dry in shade, and iron on low heat while avoiding printed or bonded details.',color:'Charcoal is a low-saturation deep grey-black; Cloud Cream is a warm off-white. Minor color variation can occur across screens and lighting conditions.',style:'Charcoal pairs well with black, washed denim and grey bottoms. Cloud Cream works naturally with brown, khaki and light denim. Tonal layering reinforces the collection’s quiet, relaxed mood.'},
  th:{intro:'ออกแบบโดยเน้นความสบายในชีวิตประจำวัน ใช้ผ้าคอตตอนผสมเนื้อแน่น ให้สัมผัสนุ่ม ทรงสวย และทนต่อการใช้งาน ผิวผ้าปัดเบาเพื่อให้ภาพรวมดูนุ่มขึ้นโดยยังคงโครงสร้างเสื้อที่ชัดเจน',fit:'ทรงหลวมแบบบ็อกซี่ ไหล่ตกเล็กน้อย และมีพื้นที่ช่วงอกมากพอ หากต้องการทรงมาตรฐานเลือกไซซ์ปกติ หรือเพิ่มหนึ่งไซซ์เพื่อการเลเยอร์ที่หลวมขึ้น',fabric:'ผ้าถักคอตตอนผสมความหนาแน่นสูง ด้านในสัมผัสนุ่ม ใช้ผ้าริบยืดคืนตัวได้ดีและเสริมตะเข็บในจุดรับแรงเพื่อรักษารูปทรง',care:'ซักน้ำเย็นหรือต่ำกว่า 30°C กลับด้านและใส่ถุงซัก ใช้น้ำยาซักผ้าอ่อนโยน ห้ามฟอกขาว ตากในที่ร่ม และรีดด้วยอุณหภูมิต่ำ',color:'Charcoal เป็นเทาดำโทนหม่น ส่วน Cloud Cream เป็นขาวครีมโทนอุ่น สีจริงอาจแตกต่างเล็กน้อยตามหน้าจอและสภาพแสง',style:'Charcoal เข้ากับสีดำ เดนิมฟอก และโทนเทาได้ดี ส่วน Cloud Cream เหมาะกับน้ำตาล กากี และเดนิมสีอ่อน การเลเยอร์โทนเดียวกันจะช่วยเน้นอารมณ์ที่สงบและผ่อนคลาย'}
};
const txt=proText[ksLang()]||proText.en;

document.getElementById('app').innerHTML=`${KS.header()}<main class="product-page"><div class="gallery">${gallery.map((g,i)=>`<img src="${g.src}" data-fallback="${g.fallback||''}" alt="${ksLocal(p.name)} ${i+1}" loading="${i>1?'lazy':'eager'}">`).join('')}</div><aside class="buybox"><small>${ksT('campaignLabel')}</small><h1>${ksLocal(p.name)}</h1><div class="price">${p.price}</div><div class="color-row"><span>${ksT('colorStyling')}</span><div class="swatches"><i class="swatch dark"></i><i class="swatch cream"></i></div></div><div class="size-label">${ksT('size')}</div><div class="sizes"><button>S</button><button>M</button><button>L</button><button>XL</button></div><div class="qty"><button>−</button><span>1</span><button>＋</button></div><button class="add">${ksT('addToCart')}</button><button class="drawer-trigger" data-drawer="product"><b>${ksT('aboutProduct')}</b><span>${ksT('tapToOpen')}　→</span></button><button class="drawer-trigger" data-drawer="color"><b>${ksT('colorStyling')}</b><span>${ksT('tapToOpen')}　→</span></button><button class="drawer-trigger" data-drawer="payment"><b>${ksT('paymentMethods')}</b><span>${ksT('tapToOpen')}　→</span></button></aside></main>${KS.footer()}<div class="drawer-backdrop"></div><aside class="info-drawer" id="infoDrawer"><button class="drawer-close" aria-label="${ksT('close')}">×</button><div class="drawer-content"></div></aside>`;

const drawer=document.querySelector('#infoDrawer'), content=drawer.querySelector('.drawer-content'), backdrop=document.querySelector('.drawer-backdrop');
function openDrawer(type){
 let html='';
 if(type==='product') html=`<h2>${ksT('productInfo')}</h2><div class="info-grid"><div><small>${ksT('weight')}</small><strong>${p.weight||'—'}</strong></div><div><small>${ksT('productStatus')}</small><strong>${ksT('stock')}</strong></div><div><small>${ksT('leadTime')}</small><strong>${p.lead||'3–5 days'}</strong></div><div><small>${ksT('size')}</small><strong>S / M / L / XL</strong></div></div><section><h3>${ksT('productDetails')}</h3><p>${txt.intro}</p></section><section><h3>${ksT('fit')}</h3><p>${txt.fit}</p></section><section><h3>${ksT('fabric')}</h3><p>${txt.fabric}</p></section><section><h3>${ksT('care')}</h3><p>${txt.care}</p></section>`;
 if(type==='color') html=`<h2>${ksT('colorStyling')}</h2><section><h3>${ksT('colorNote')}</h3><p>${txt.color}</p><div class="color-cards"><div><i class="color-chip charcoal"></i><b>Charcoal</b><small>Low-saturation deep grey</small></div><div><i class="color-chip cloud"></i><b>Cloud Cream</b><small>Warm soft ivory</small></div></div></section><section><h3>${ksT('styling')}</h3><p>${txt.style}</p></section>`;
 if(type==='payment') html=`<h2>${ksT('paymentMethods')}</h2><div class="payment-note">${ksLang()==='zh'?'以下为页面展示用支付结构，正式上线后应以实际接入的支付服务商及可用渠道为准。':ksLang()==='zht'?'以下為頁面展示用支付結構，正式上線後應以實際接入的支付服務商及可用渠道為準。':ksLang()==='th'?'ตัวเลือกด้านล่างเป็นตัวอย่างสำหรับหน้าเว็บไซต์ ช่องทางจริงขึ้นอยู่กับผู้ให้บริการชำระเงินที่เชื่อมต่อ':'The options below are interface examples. Actual availability depends on the payment provider connected to the live store.'}</div>${[ksT('card'),ksT('qr'),ksT('banking'),ksT('installment'),ksT('wallet'),ksT('transfer')].map((x,i)=>`<div class="pay-row"><b>${x}</b><span>${['VISA · Mastercard · JCB','QR · PromptPay','KBank · SCB · Krungsri','Up to 10 months','LINE Pay · Wallet','Bank account'][i]}　⌄</span></div>`).join('')}`;
 content.innerHTML=html; drawer.classList.add('open');backdrop.classList.add('open');document.body.classList.add('drawer-open');
}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');document.body.classList.remove('drawer-open')}
document.querySelectorAll('.drawer-trigger').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.drawer)));drawer.querySelector('.drawer-close').onclick=closeDrawer;backdrop.onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
document.querySelectorAll('.sizes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sizes button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
KS.bind();
